/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class homework10 */

#ifndef _Included_homework10
#define _Included_homework10
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     homework10
 * Method:    is_multiple5
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_homework10_is_1multiple5
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
